# Generated by Django 4.1.1 on 2022-11-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_info_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portada_dos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('imagen', models.ImageField(upload_to='imagenes/')),
            ],
        ),
    ]
