# Generated by Django 4.1.1 on 2022-11-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0004_horario_productos_promociones_trabajos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('imagen', models.ImageField(upload_to='imagenes/')),
                ('especificacion', models.TextField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
