# Generated by Django 4.1.1 on 2022-11-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0005_recomendaciones_delete_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendaciones',
            name='especificacion',
            field=models.TextField(max_length=900),
        ),
    ]
